# Generated by Django 5.1 on 2024-09-10 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ExamName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InputSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_description', models.TextField()),
                ('details', models.TextField()),
                ('question_video', models.FileField(blank=True, null=True, upload_to='input_suggestion/videos/')),
                ('question_link', models.URLField(blank=True, null=True)),
                ('other_text', models.TextField(blank=True, null=True)),
                ('exam_name', models.CharField(max_length=255)),
                ('subject_name', models.CharField(max_length=255)),
                ('area_name', models.CharField(max_length=255)),
                ('part_name', models.CharField(blank=True, max_length=255, null=True)),
                ('topic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_question', models.CharField(default='mcq1', max_length=100)),
                ('exam_name', models.CharField(max_length=100)),
                ('exam_stage', models.CharField(blank=True, max_length=100, null=True)),
                ('exam_year', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('script', models.TextField(blank=True, null=True)),
                ('marks', models.FloatField(default=0.0)),
                ('negative_marks', models.FloatField(default=0.0)),
                ('degree_of_difficulty', models.CharField(max_length=100)),
                ('question_sub_type', models.CharField(choices=[('simple_type', 'Simple Type'), ('r_and_a_type', 'R & A Type'), ('list_type_1', 'List Type 1'), ('list_type_2', 'List Type 2'), ('true_and_false_type', 'True & False'), ('fill_in_the_blank_type', 'Fill in the Blank')], default='simple_type', max_length=100)),
                ('question_number', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('question_part', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('assertion', models.TextField(blank=True, null=True)),
                ('question_part_first', models.TextField(blank=True, null=True)),
                ('list_1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('list_2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('list_1_row1', models.CharField(blank=True, max_length=255, null=True)),
                ('list_1_row2', models.CharField(blank=True, max_length=255, null=True)),
                ('list_1_row3', models.CharField(blank=True, max_length=255, null=True)),
                ('list_1_row4', models.CharField(blank=True, max_length=255, null=True)),
                ('list_1_row5', models.CharField(blank=True, max_length=255, null=True)),
                ('list_1_row6', models.CharField(blank=True, max_length=255, null=True)),
                ('list_1_row7', models.CharField(blank=True, max_length=255, null=True)),
                ('list_1_row8', models.CharField(blank=True, max_length=255, null=True)),
                ('list_2_row1', models.CharField(blank=True, max_length=255, null=True)),
                ('list_2_row2', models.CharField(blank=True, max_length=255, null=True)),
                ('list_2_row3', models.CharField(blank=True, max_length=255, null=True)),
                ('list_2_row4', models.CharField(blank=True, max_length=255, null=True)),
                ('list_2_row5', models.CharField(blank=True, max_length=255, null=True)),
                ('list_2_row6', models.CharField(blank=True, max_length=255, null=True)),
                ('list_2_row7', models.CharField(blank=True, max_length=255, null=True)),
                ('list_2_row8', models.CharField(blank=True, max_length=255, null=True)),
                ('question_part_third', models.TextField(blank=True, null=True)),
                ('answer_option_a', models.TextField(blank=True, null=True)),
                ('answer_option_b', models.TextField(blank=True, null=True)),
                ('answer_option_c', models.TextField(blank=True, null=True)),
                ('answer_option_d', models.TextField(blank=True, null=True)),
                ('correct_answer_choice', models.CharField(blank=True, max_length=1, null=True)),
                ('correct_answer_description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Question Images')),
                ('subject_name', models.CharField(max_length=100)),
                ('area_name', models.CharField(max_length=100)),
                ('part_name', models.CharField(max_length=100)),
                ('chapter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('topic_name', models.CharField(blank=True, max_length=255, null=True)),
                ('table_head_a', models.CharField(blank=True, max_length=100, null=True)),
                ('table_head_b', models.CharField(blank=True, max_length=100, null=True)),
                ('table_head_c', models.CharField(blank=True, max_length=100, null=True)),
                ('table_head_d', models.CharField(blank=True, max_length=100, null=True)),
                ('head_a_data1', models.CharField(blank=True, max_length=100, null=True)),
                ('head_a_data2', models.CharField(blank=True, max_length=100, null=True)),
                ('head_a_data3', models.CharField(blank=True, max_length=100, null=True)),
                ('head_a_data4', models.CharField(blank=True, max_length=100, null=True)),
                ('head_b_data1', models.CharField(blank=True, max_length=100, null=True)),
                ('head_b_data2', models.CharField(blank=True, max_length=100, null=True)),
                ('head_b_data3', models.CharField(blank=True, max_length=100, null=True)),
                ('head_b_data4', models.CharField(blank=True, max_length=100, null=True)),
                ('head_c_data1', models.CharField(blank=True, max_length=100, null=True)),
                ('head_c_data2', models.CharField(blank=True, max_length=100, null=True)),
                ('head_c_data3', models.CharField(blank=True, max_length=100, null=True)),
                ('head_c_data4', models.CharField(blank=True, max_length=100, null=True)),
                ('head_d_data1', models.CharField(blank=True, max_length=100, null=True)),
                ('head_d_data2', models.CharField(blank=True, max_length=100, null=True)),
                ('head_d_data3', models.CharField(blank=True, max_length=100, null=True)),
                ('head_d_data4', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InputSuggestionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='input_suggestion/documents/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='question_bank.inputsuggestion')),
            ],
        ),
        migrations.CreateModel(
            name='InputSuggestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='input_suggestion/images/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='question_bank.inputsuggestion')),
            ],
        ),
        migrations.CreateModel(
            name='PartName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='question_bank.area')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='question_bank.partname')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='question_bank.examname')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='question_bank.subject'),
        ),
        migrations.CreateModel(
            name='TopicName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='question_bank.chaptername')),
            ],
        ),
    ]
