# Generated by Django 5.1 on 2024-09-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputsuggestion',
            name='chapter_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inputsuggestion',
            name='question_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
