# Generated by Django 5.1 on 2024-09-11 08:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0002_inputsuggestion_chapter_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
