# Generated by Django 5.0.6 on 2024-09-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0006_quoteidiomphrase_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteidiomphrase',
            name='meaning',
            field=models.TextField(blank=True, null=True),
        ),
    ]
