# Generated by Django 5.1 on 2024-09-21 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0009_remove_quoteidiomphrase_area_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteidiomphrase',
            name='areas',
        ),
        migrations.RemoveField(
            model_name='quoteidiomphrase',
            name='chapters',
        ),
        migrations.RemoveField(
            model_name='quoteidiomphrase',
            name='exams',
        ),
        migrations.RemoveField(
            model_name='quoteidiomphrase',
            name='parts',
        ),
        migrations.RemoveField(
            model_name='quoteidiomphrase',
            name='subjects',
        ),
        migrations.AddField(
            model_name='quoteidiomphrase',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='question_bank.area'),
        ),
        migrations.AddField(
            model_name='quoteidiomphrase',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='question_bank.chaptername'),
        ),
        migrations.AddField(
            model_name='quoteidiomphrase',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='question_bank.examname'),
        ),
        migrations.AddField(
            model_name='quoteidiomphrase',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='question_bank.partname'),
        ),
        migrations.AddField(
            model_name='quoteidiomphrase',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='question_bank.subject'),
        ),
        migrations.AlterField(
            model_name='quoteidiomphrase',
            name='topics',
            field=models.ManyToManyField(to='question_bank.topicname'),
        ),
    ]
