# Generated by Django 5.1 on 2024-09-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0010_remove_quoteidiomphrase_areas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteidiomphrase',
            name='area',
        ),
        migrations.RemoveField(
            model_name='quoteidiomphrase',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='quoteidiomphrase',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='quoteidiomphrase',
            name='part',
        ),
        migrations.RemoveField(
            model_name='quoteidiomphrase',
            name='subject',
        ),
        migrations.AddField(
            model_name='quoteidiomphrase',
            name='areas',
            field=models.ManyToManyField(blank=True, to='question_bank.area'),
        ),
        migrations.AddField(
            model_name='quoteidiomphrase',
            name='chapters',
            field=models.ManyToManyField(blank=True, to='question_bank.chaptername'),
        ),
        migrations.AddField(
            model_name='quoteidiomphrase',
            name='exams',
            field=models.ManyToManyField(blank=True, to='question_bank.examname'),
        ),
        migrations.AddField(
            model_name='quoteidiomphrase',
            name='parts',
            field=models.ManyToManyField(blank=True, to='question_bank.partname'),
        ),
        migrations.AddField(
            model_name='quoteidiomphrase',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='question_bank.subject'),
        ),
        migrations.AlterField(
            model_name='quoteidiomphrase',
            name='topics',
            field=models.ManyToManyField(blank=True, to='question_bank.topicname'),
        ),
    ]
