# Generated by Django 5.1 on 2024-09-23 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0011_remove_quoteidiomphrase_area_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteidiomphrase',
            name='admin_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_approved_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quoteidiomphrase',
            name='rejected_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoteidiomphrase',
            name='staff_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_approved_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quoteidiomphrase',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('staff_approved', 'Staff Approved'), ('admin_approved', 'Admin Approved'), ('rejected', 'Rejected')], default='pending', max_length=15),
        ),
    ]
