# Generated by Django 5.1 on 2024-09-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0012_quoteidiomphrase_admin_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='evergreen_index',
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
    ]
