# Generated by Django 5.1 on 2024-09-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0013_questionbank_evergreen_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputsuggestion',
            name='evergreen_index',
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='inputsuggestion',
            name='language',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inputsuggestion',
            name='script',
            field=models.TextField(blank=True, null=True),
        ),
    ]
