# Generated by Django 5.1 on 2024-10-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0014_inputsuggestion_evergreen_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionbank',
            name='area_name',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='chapter_name',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='exam_name',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='part_name',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='subject_name',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='topic_name',
        ),
        migrations.AddField(
            model_name='questionbank',
            name='area_name',
            field=models.ManyToManyField(related_name='questions', to='question_bank.area'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='chapter_name',
            field=models.ManyToManyField(blank=True, related_name='questions', to='question_bank.chaptername'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='exam_name',
            field=models.ManyToManyField(related_name='questions', to='question_bank.examname'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='part_name',
            field=models.ManyToManyField(related_name='questions', to='question_bank.partname'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='subject_name',
            field=models.ManyToManyField(related_name='questions', to='question_bank.subject'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='topic_name',
            field=models.ManyToManyField(blank=True, related_name='questions', to='question_bank.topicname'),
        ),
    ]
