# Generated by Django 5.1 on 2024-10-03 08:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0016_weeklyreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('this_week', 'This Week Report'), ('earlier', 'Earlier Report')], max_length=20)),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='reports/csv/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/pdf/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='WeeklyReport',
        ),
    ]
