# Generated by Django 5.1 on 2024-10-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0017_report_delete_weeklyreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='csv_file',
        ),
        migrations.RemoveField(
            model_name='report',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='report',
            name='fill_blank_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='list_1_type_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='list_2_type_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='ra_type_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='simple_type_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='total_phrases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='total_suggestions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='true_false_type_count',
            field=models.IntegerField(default=0),
        ),
    ]
