# Generated by Django 5.1 on 2024-10-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0018_remove_report_csv_file_remove_report_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
