# Generated by Django 5.1 on 2024-10-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_bank', '0019_alter_report_report_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputsuggestion',
            name='area_name',
        ),
        migrations.RemoveField(
            model_name='inputsuggestion',
            name='chapter_name',
        ),
        migrations.RemoveField(
            model_name='inputsuggestion',
            name='exam_name',
        ),
        migrations.RemoveField(
            model_name='inputsuggestion',
            name='part_name',
        ),
        migrations.RemoveField(
            model_name='inputsuggestion',
            name='subject_name',
        ),
        migrations.RemoveField(
            model_name='inputsuggestion',
            name='topic_name',
        ),
        migrations.AddField(
            model_name='inputsuggestion',
            name='area_name',
            field=models.ManyToManyField(related_name='input_suggestions', to='question_bank.area'),
        ),
        migrations.AddField(
            model_name='inputsuggestion',
            name='chapter_name',
            field=models.ManyToManyField(blank=True, related_name='input_suggestions', to='question_bank.chaptername'),
        ),
        migrations.AddField(
            model_name='inputsuggestion',
            name='exam_name',
            field=models.ManyToManyField(related_name='input_suggestions', to='question_bank.examname'),
        ),
        migrations.AddField(
            model_name='inputsuggestion',
            name='part_name',
            field=models.ManyToManyField(related_name='input_suggestions', to='question_bank.partname'),
        ),
        migrations.AddField(
            model_name='inputsuggestion',
            name='subject_name',
            field=models.ManyToManyField(related_name='input_suggestions', to='question_bank.subject'),
        ),
        migrations.AddField(
            model_name='inputsuggestion',
            name='topic_name',
            field=models.ManyToManyField(blank=True, related_name='input_suggestions', to='question_bank.topicname'),
        ),
    ]
