# Generated by Django 5.1 on 2024-09-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_galleryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
