# Generated by Django 5.1 on 2024-09-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_galleryitem_file_alter_galleryitem_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/thumbnails/'),
        ),
    ]
