name: Django Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/hajela_ias_academy:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/hajela_ias_academy:latest

    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_PRIVATE_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/hajela_ias_academy:latest
          docker stop hajela_ias_academy_container || true
          docker rm hajela_ias_academy_container || true
          docker run -d --name hajela_ias_academy_container -p 80:8000 --env-file .env ${{ secrets.DOCKER_USERNAME }}/hajela_ias_academy:latest
