name: Deploy Django Project to VPS

on:
  push:
    branches:
      - main  # Change to your main branch name if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VPS
      run: |
        ssh your_vps_user@your_vps_ip << 'EOF'
        cd /var/www/hia_bak/hajela_ias_academy
        git pull origin main
        docker-compose down
        docker-compose up -d --build
        EOF
